version: "3"

tasks:
  repo:pull:
    desc: "Git pull in every repositories/* directory"
    cmds:
      - |
        set -eu
        for d in repositories/*; do
            [ -d "$d" ] || continue
            echo "==> syncing $d"
            (cd "$d" && git checkout main && git pull)
        done

  repo:start:
    desc: "Start repositories matching pattern (e.g. task repo:start -- twin)"
    cmds:
      - |
        set -eu
        pattern="{{.CLI_ARGS}}"

        matched=0

        # Special-case: dev proxy lives at repo root
        case "proxy" in
          *"$pattern"*)
            echo "==> starting proxy (repo root)"
            docker compose up -d
            matched=1
            ;;
        esac

        for d in repositories/*; do
          [ -d "$d" ] || continue
          name="$(basename "$d")"
          case "$name" in
            *"$pattern"*)
              echo "==> starting $name"
              (cd "$d" && docker compose up -d)
              matched=1
              ;;
          esac
        done

        if [ "$matched" -eq 0 ]; then
          echo "No repositories matched pattern: '$pattern'" >&2
          exit 1
        fi

  repo:stop:
    desc: "Stop repositories matching pattern (e.g. task repo:stop -- twin)"
    cmds:
      - docker compose down
      - |
        set -eu
        pattern="{{.CLI_ARGS}}"

        matched=0

        # Special-case: dev proxy lives at repo root
        case "proxy" in
          *"$pattern"*)
            echo "==> stopping proxy (repo root)"
            docker compose down
            matched=1
            ;;
        esac

        for d in repositories/*; do
          [ -d "$d" ] || continue
          name="$(basename "$d")"
          case "$name" in
            *"$pattern"*)
              echo "==> stopping $name"
              (cd "$d" && docker compose down)
              matched=1
              ;;
          esac
        done

        if [ "$matched" -eq 0 ]; then
          echo "No repositories matched pattern: '$pattern'" >&2
          exit 1
        fi

  repo:env:pack:
    desc: "Scan repositories/**/.env and pack them into a zip preserving structure"
    cmds:
      - |
        set -e
        rm -f tmp/env-pack.zip
        mkdir -p tmp
        cd repositories
        files=$(find . -type f -name ".env")
        if [ -z "$files" ]; then
          echo "No .env files found"
          exit 0
        fi
        zip -q ../tmp/env-pack.zip $files
        echo "Created tmp/env-pack.zip"

  repo:env:extract:
    desc: "Extract env-pack.zip and restore .env files safely"
    cmds:
      - |
        set -e
        if [ ! -f tmp/env-pack.zip ]; then
          echo "Archive tmp/env-pack.zip not found"
          exit 1
        fi

        rm -rf tmp/env-pack
        mkdir -p tmp/env-pack
        unzip -q tmp/env-pack.zip -d tmp/env-pack

        cd tmp/env-pack
        find . -type f -name ".env" | while read src; do
          dst="../../repositories/${src#./}"
          dst_dir=$(dirname "$dst")

          mkdir -p "$dst_dir"

          if [ -f "$dst" ]; then
            if cmp -s "$src" "$dst"; then
              continue
            else
              echo "WARN: existing .env differs, skipping: $dst"
              continue
            fi
          fi

          cp "$src" "$dst"
          echo "Restored $dst"
        done

  vscode:workspace:
    desc: Generate deterministic VS Code multi-root workspace from repositories/*
    cmds:
      - |
        set -euo pipefail

        WORKSPACE_FILE="celine.code-workspace"

        repos=$(find repositories -mindepth 1 -maxdepth 1 -type d | sort)

        {
          echo "{"
          echo '  "folders": ['
          echo '    { "path": ".", "name": "celine-dev" },'
          first=1
          for repo in $repos; do
            if [ -d "$repo/.git" ] || [ -f "$repo/.git" ]; then
              if [ $first -eq 0 ]; then
                echo ","
              fi
              first=0
              printf '    { "path": "%s" }' "$repo"
            fi
          done

          echo ""
          echo "  ],"
          echo '  "settings": {}'
          echo "}"
        } > "$WORKSPACE_FILE"

        echo "Generated $WORKSPACE_FILE"

  start:proxy:
    desc: Start service proxy
    deps: [start:policies]
    cmds:
      - docker compose up -d

  start:pipelines:services:
    deps: [start:pipelines:db]
    desc: Start pipelines services
    dir: repositories/celine-pipelines
    cmds:
      - docker compose up -d marquez-web marquez-api prefect-server prefect-worker

  start:pipelines:db:
    desc: Start pipelines services
    dir: repositories/celine-pipelines
    cmds:
      - docker compose up -d datasets-db

  start:policies:
    desc: Start pipelines services
    dir: repositories/celine-policies
    cmds:
      - docker compose up -d

  start:dataset-api:
    desc: Start dataset-api services
    deps: [start:pipelines]
    dir: repositories/dataset-api
    cmds:
      - docker compose up -d

  start:db:
    desc: Start dataset-api services
    dir: repositories/celine-pipelines
    cmds:
      - docker compose up -d datasets-db

  start:digital-twin:
    desc: Start dataset-api services
    deps: [start:dataset-api]
    dir: repositories/digital-twin
    cmds:
      - docker compose up -d

  start:rec-registry:
    desc: Start rec-registry
    dir: repositories/rec-registry
    cmds:
      - docker compose up -d

  start:superset:
    desc: Start superset services
    dir: repositories/celine-dashboards
    cmds:
      - docker compose up -d

  start:base:
    desc: Start dev services
    cmds:
      - task: start:proxy
      - task: start:pipelines

  start:dev:api:
    desc: start services for api development
    cmds:
      - task: start:proxy
      - task: start:pipelines:db
      - task: start:policies
